#server 配置
server:
  port: 8080
  servlet:
    path: /
    session:
      timeout: 60
  tomcat:
    uri-encoding: UTF-8
  address: 127.0.0.1
#datasource
spring:
  datasource:
    url: jdbc:mysql://59.110.225.219:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: owen150
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true