#server 配置
server:
  port: 8080
  servlet:
    path: /
    session:
      timeout: 60
  tomcat:
    uri-encoding: UTF-8
  address: 127.0.0.1
#datasource
spring:
  datasource:
    url: jdbc:mysql://59.110.225.219:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: owen150
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      initial-size: 1
      # 最小连接池数量
      min-idle: 1
      # 最大连接池数量
      max-active: 20
      # 这里建议配置为TRUE，防止取到的连接不可用
      test-on-borrow: true
      # 配置获取连接等待超时的时间
      max-wait: 10000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
